# Ecommerce Purchases Exercise

In this Exercise you will be given some Fake Data about some purchases done through Amazon! Just go ahead and follow the directions and try your best to answer the questions and complete the tasks. Feel free to reference the solutions. Most of the tasks can be solved in different ways. For the most part, the questions get progressively harder.

Please excuse anything that doesn't make "Real-World" sense in the dataframe, all the data is fake and made-up.

Also note that all of these questions can be answered with one line of code.

In [29]:
# importing the libraries..

import numpy as np
import pandas as pd

In [30]:
# Loading the data in DataFrame.

df = pd.read_csv('Ecommerce Purchases')

In [3]:
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [4]:
df.describe()

        Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [6]:
# Checking the languages spoken by the customers

df['Language'].unique()

array(['el', 'fr', 'de', 'es', 'ru', 'pt', 'zh', 'en', 'it'], dtype=object)

In [7]:
# Checking the english language spoken customer count.

df[df['Language']=='en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [31]:
df.head(30)   # checking the top 30 list in DataFrame..

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63
10,"650 Elizabeth Park\nLake Maria, LA 13526-2530",65 Yn,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_1 like M...,"Strickland, Michael and Gonzales",180036417827355,02/17,754,Voyager,ustewart@hotmail.com,"Development worker, community",26.59.93.1,el,96.89
11,"349 Laurie Parks\nThomasview, ID 08970",30 kK,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,Kim-Oliver,869975209012056,06/26,9717,JCB 15 digit,johnnymiller@coleman.com,Diagnostic radiographer,128.222.40.234,en,19.26
12,"733 Heather Rest Apt. 670\nBoltonport, UT 78662",69 DO,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 ...,Moore-Martin,5115990487067905,05/26,119,VISA 16 digit,tholt@hotmail.com,"Surveyor, quantity",236.71.234.240,en,39.65
13,"118 Melton Via Suite 681\nAlexanderbury, FL 32104",36 bu,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Keller PLC,4603635169938574,01/25,557,VISA 16 digit,caitlin57@yahoo.com,"Accountant, chartered public finance",84.212.92.11,it,8.93
14,"8774 Jason Keys Suite 427\nEast Scottborough, ...",70 zH,AM,Mozilla/5.0 (Windows 98; it-IT; rv:1.9.2.20) G...,"Leach, Howe and Ferguson",869967499275071,09/22,427,VISA 16 digit,aburns@yahoo.com,Acupuncturist,50.25.148.1,de,24.18
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78
16,5283 Thomas Trafficway Suite 343\nEast Brittne...,31 ho,AM,Opera/9.73.(Windows NT 6.2; sl-SI) Presto/2.9....,"Stanton, Villanueva and Swanson",676121145525,06/22,285,Diners Club / Carte Blanche,griffincatherine@wilson.com,"Therapist, art",8.145.170.52,de,84.44
17,950 Jacqueline Village Apt. 592\nPort Kimberly...,23 Rh,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Fernandez, Melton and Gilbert",3337515540944084,01/26,771,American Express,stacymitchell@hall.com,"Designer, jewellery",223.25.125.61,el,58.68
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
20,"7383 George Village\nLake Jamesview, CO 79828",23 dk,PM,Mozilla/5.0 (Windows; U; Windows NT 4.0) Apple...,"Santana, Montes and Pierce",6011833038852776,03/22,740,Maestro,zstephenson@smith.info,Public relations officer,250.71.54.180,de,30.33
21,"282 Miller Valleys Suite 404\nWilkinsonbury, M...",24 RZ,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Guzman-Reese,5491255326230898,03/25,506,JCB 16 digit,rsmith@hotmail.com,"Presenter, broadcasting",125.58.66.253,it,90.93
22,"625 Laura Summit Suite 112\nShortmouth, AK 97156",45 oa,PM,Mozilla/5.0 (Windows 95) AppleWebKit/5342 (KHT...,Burnett Ltd,3158663456056588,07/22,508,Discover,chambersmichael@gmail.com,Retail manager,65.106.61.141,en,33.62
23,"25292 Shepherd Trail Apt. 798\nRussellmouth, S...",31 pS,PM,Mozilla/5.0 (compatible; MSIE 5.0; Windows 98;...,Cruz Inc,502010078983,02/23,60,VISA 13 digit,ltaylor@gardner-meadows.com,Field seismologist,25.193.145.116,ru,97.97
24,Unit 3046 Box 3197\nDPO AE 61496-4172,62 Ac,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows CE;...,Morris PLC,4749728852401144,07/18,11,JCB 15 digit,james07@yahoo.com,Musician,21.113.231.220,es,85.31
25,"80797 Ryan Trail Apt. 752\nAaronhaven, MI 0622...",66 SO,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_1...,Saunders-Mendez,869938033091779,05/19,901,Voyager,madison41@mooney.com,Training and development officer,67.26.186.226,de,6.25
26,"5334 Sheppard Fort\nNorth Kirsten, ND 71170",40 ND,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3)...,"Stephens, Johnson and Combs",60488441233,03/19,70,VISA 13 digit,mlogan@gmail.com,Barrister's clerk,61.197.134.185,en,17.75
27,"5015 Smith Harbors\nSouth Ashley, OK 81283",34 JQ,PM,Opera/9.75.(Windows NT 6.0; en-US) Presto/2.9....,"Levine, Shaw and Jenkins",869948145612941,12/16,310,Diners Club / Carte Blanche,michael35@hotmail.com,Careers adviser,177.220.131.93,es,39.40
28,"50533 Cooper Cliffs\nNorth Jonathanberg, MD 20482",17 kP,PM,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,Reed Inc,180026477662982,11/24,16,JCB 15 digit,khandeborah@yahoo.com,"Scientist, research (life sciences)",142.131.235.225,es,70.75
29,"30755 Joshua Plaza Apt. 567\nWest Susanton, FM...",93 OP,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_7...,Goodwin Ltd,4170734785397597,07/22,319,Maestro,stonekaren@yahoo.com,Recycling officer,218.189.145.248,it,82.16

In [9]:
df['Job'].value_counts()   # seems like there are various category of jobs customers are doing.

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
                                 ..
Prison officer                    7
Editor, film/video                6
Actuary                           6
Information systems manager       5
Investment analyst                5
Name: Job, Length: 623, dtype: int64

In [10]:
df.columns  # here are all the columns of this dataset

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [11]:
# Checking how many customers were in the lawyer profession.

df[df['Job']=='Lawyer'].count()


# seems like there are very few in the lawyer position.

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [12]:
df.columns  # here again we checking the dataset columns.
            # Sorry i have very poor memory storage in my brain....STML..ahh

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [13]:
# lets move ahead.

In [14]:
df['AM or PM'].value_counts()  # Seems like most of the customers do purchases after midnoon.

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [15]:
df['Job'].value_counts().head(5)   # here are the list of top 5 most choosen job profession by our customers

                                   # F%%%ing Rich! ahem..

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

** Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction? **

In [16]:
df[df['Lot']=='90 WT']['Purchase Price']   # just checking.....

513    75.1
Name: Purchase Price, dtype: float64

In [17]:
# So, here are the figure.shape.curve.size of the dataset....

df.shape

(10000, 14)

In [18]:
df.columns # ahmm. again here we go....

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

** What is the email of the person with the following Credit Card Number: 4926535242672853 **

In [19]:
df[df['Credit Card']==4926535242672853]['Email']       # just spying......

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [21]:
# So! here is the the list of credit card provider 

df['CC Provider'].value_counts()

JCB 16 digit                   1716
VISA 16 digit                  1715
JCB 15 digit                    868
American Express                849
Maestro                         846
Voyager                         829
Discover                        817
Mastercard                      816
VISA 13 digit                   777
Diners Club / Carte Blanche     767
Name: CC Provider, dtype: int64

* How many people have American Express as their Credit Card Provider *and made a purchase above $95 ?**

In [22]:
df[(df['CC Provider']=='American Express') & (df['Purchase Price']>95)].count()  # hmm

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [23]:
df.columns  # ...

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [24]:
df['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

** Hard: How many people have a credit card that expires in 2025? **

In [26]:
df[df['CC Exp Date'].apply(lambda exp: exp[3:])=='25'].count()

Address             1033
Lot                 1033
AM or PM            1033
Browser Info        1033
Company             1033
Credit Card         1033
CC Exp Date         1033
CC Security Code    1033
CC Provider         1033
Email               1033
Job                 1033
IP Address          1033
Language            1033
Purchase Price      1033
dtype: int64

** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **

In [27]:
df['Email'].head(20)

0                  pdunlap@yahoo.com
1                 anthony41@reed.com
2     amymiller@morales-harrison.com
3        brent16@olson-robinson.info
4        christopherwright@gmail.com
5                  ynguyen@gmail.com
6                 olivia04@yahoo.com
7               phillip48@parks.info
8               kdavis@rasmussen.com
9           qcoleman@hunt-huerta.com
10              ustewart@hotmail.com
11          johnnymiller@coleman.com
12                 tholt@hotmail.com
13               caitlin57@yahoo.com
14                  aburns@yahoo.com
15                amanda39@yahoo.com
16       griffincatherine@wilson.com
17            stacymitchell@hall.com
18                hannah63@yahoo.com
19              ruiznicole@gmail.com
Name: Email, dtype: object

In [28]:
#  here are the top 5 most popular email providers/hosts 


df['Email'].apply(lambda x: x.lower().split('@')[1]).value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64

#  And yet lot more to do......